services:
  mongodb:
    image: someshwarsangaraju/mongodb:v1
    container_name: mongodb
  catalogue:
    image: someshwarsangaraju/catalogue:v1
    container_name: catalogue
    depends_on: 
      -mongodb
  redis:
    image: someshwarsangaraju/redis:7
    container_name: redis
  rabbitmq:
    image: someshwarsangaraju/rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  mysql:
    image: someshwarsangaraju/mysql:v1
    container_name: mysql
  user:
    image: someshwarsangaraju/user:v1
    container_name: user
    depends_on: 
      -mongodb
      -redis
  cart:
    image: someshwarsangaraju/cart:v1
    container_name: cart
    depends_on: 
      -redis
  shipping:
    image: someshwarsangaraju/shipping:v1
    container_name: shipping
    depends_on: 
      -mysql
  payment:
    image: someshwarsangaraju/payment:v1
    container_name: payment
    depends_on: 
      -rabbitmq
  frontend:
    image: someshwarsangaraju/frontend:v1
    container_name: frontend
    depends_on: 
      -user
      -cart
      -shipping
      -payment
      -catalogue
  networks:
    default:
      driver: bridge
      name: roboshop
      external: false




