services:
  mongodb:
    image: someshwarsangaraju/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb: /data/db
  catalogue:
    image: someshwarsangaraju/catalogue:v1
    container_name: catalogue
    depends_on: 
      - mongodb
  redis:
    image: someshwarsangaraju/redis:7
    container_name: redis
    volumes:
      - redis: /data
  rabbitmq:
    image: someshwarsangaraju/rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq: /var/lib/rabbitmq
  mysql:
    image: someshwarsangaraju/mysql:v1
    container_name: mysql
    volumes:
      - mysql: /var/lib/mysql
  user:
    image: someshwarsangaraju/user:v1
    container_name: user
    depends_on: 
      - mongodb
      - redis
  cart:
    image: someshwarsangaraju/cart:v1
    container_name: cart
    depends_on: 
      - redis
      - catalogue
  shipping:
    image: someshwarsangaraju/shipping:v1
    container_name: shipping
    depends_on: 
      - mysql
      - cart
  payment:
    image: someshwarsangaraju/payment:v1
    container_name: payment
    depends_on: 
      - rabbitmq
      - user
      - cart
  frontend:
    image: someshwarsangaraju/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on: 
      - user
      - cart
      - shipping
      - payment
      - catalogue
networks:
  default:
    driver: bridge
    name: roboshop
    external: false
volumes:
  - mongodb:
  - mysql:
  - redis:
  - rabbitmq:


